Adding associate-eip, changing logic in dns-server-boot and dns-server-init

diff --git a/files/sbin/associate-eip b/files/sbin/associate-eip
--- a/files/sbin/associate-eip
+++ b/files/sbin/associate-eip
@@ -1,7 +1,6 @@
 #!/bin/bash
 #
-# This script is ran every time this system is initialized, typically
-# during the AMI's first boot.
+# This script associates an EIP to this instance
 
 LOGGER_BIN='/usr/bin/logger'
 
@@ -11,7 +10,7 @@ if [ ! -x $LOGGER_BIN ]; then
     echo "ERROR: '$BASH_SOURCE' Line: '$LINENO'"
     exit 2
 else
-    LOGGER="$LOGGER_BIN --stderr --priority local7.info --tag dns-server-init"
+    LOGGER="$LOGGER_BIN --stderr --priority local7.info --tag associate-eip"
 fi
 
 # Source the consul connection details from the metadata api
@@ -65,16 +64,27 @@ while [ "$KEYS_UP" != "0" ]; do
     fi
 done
 
-# Retrieve and save the private key to be used for communication to dnsconfig@svn.mozilla.org
-PRIVATE_KEY_FILE="/var/named/.ssh/id_rsa"
-curl -s --output $PRIVATE_KEY_FILE "${CONSUL}/SSHPrivateKey?raw=1"
-chmod 0600 $PRIVATE_KEY_FILE
+elasticip_id=$(curl -s $CONSUL/ElasticIP?raw=1)
+instance_id=$(curl -s -fq http://169.254.169.254/latest/meta-data/instance-id)
+local_ip=$(curl -s -fq http://169.254.169.254/latest/meta-data/local-ipv4)
 
-if [[ ! -s $PRIVATE_KEY_FILE ]]; then
-   $LOGGER "ERROR: Failed to get ssh private key from ${CONSUL}/SSHPrivateKey"
-   exit 1
+EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
+EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
+
+# If we didn't find our elasticip in Consul, look for it in our CloudFormation stack outputs
+if [ -z "${elasticip_id}" ]; then
+  elasticip_id = $(aws --region $EC2_REGION cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey == ElasticIP].OutputValue' --output text)
 fi
 
-# Run the initial checkout
-export SVN_SSH="/usr/bin/ssh -q -oStrictHostKeyChecking=no -i$PRIVATE_KEY_FILE"
-cd /var/named/chroot/var/named/ && /usr/bin/svn checkout --non-interactive --config-dir /var/named/.subversion svn+ssh://dnsconfig@svn.mozilla.org/sysadmins/dnsconfig/ .
+if [[ -z "${instance_id}" ]]; then
+    $LOGGER "ERROR: Instance ID not found"
+    exit 1
+fi
+
+aws ec2 associate-address --instance-id ${instance_id} --allocation-id ${elasticip_id} --private-ip-address ${local_ip} --region ${EC2_REGION}
+RV=$?
+
+if [[ ${RV} != 0 ]]; then
+    $LOGGER "ERROR: Unable to associate elastic IP ${elasticip_id} to instance ${instance_id}"
+    exit 1
+fi
diff --git a/files/sbin/dns-server-boot b/files/sbin/dns-server-boot
--- a/files/sbin/dns-server-boot
+++ b/files/sbin/dns-server-boot
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+LOGGER_BIN='/usr/bin/logger'
+
+# Set up the logger command if the binary is installed
+if [ ! -x $LOGGER_BIN ]; then
+    echo "ERROR: 'logger' binary not found - Aborting"
+    echo "ERROR: '$BASH_SOURCE' Line: '$LINENO'"
+    exit 2
+else
+    LOGGER="$LOGGER_BIN --stderr --priority local7.info --tag dns-server-boot"
+fi
+
 # Exit on any error
 set -e
 
@@ -13,8 +24,14 @@ chmod 0640 /var/named/chroot/etc/rndc.key
 if [[ ! -d /var/named/chroot/var/named/.svn ]]; then
    sudo -u named-update /usr/local/sbin/dns-server-init
 else
-   sudo -u named-update /usr/local/bin/namedctl update
+   sudo -u named-update /usr/local/bin/namedctl update | $LOGGER
 fi
 
-# Boot
-service named start
+# Start named
+service named start 2>&1 | $LOGGER
+
+# Run a service test
+namedctl test | $LOGGER
+
+# Associate our EIP
+associate-eip
